import requests
import re
from supabase import create_client

#Parsing the .env file to get the key, the URL of the database, and API Token for API Tennis
env_variables = {}
with open(".env") as file:
    for line in file:
        key, value = line.strip().split("=",1)
        env_variables[key] = value.strip('"').strip("'")

supabase_url = env_variables["DATABASE_URL"]
supabase_key = env_variables["DATABASE_KEY"]
tennis_api_token = env_variables["API_TOKEN"]

#Base URL of the Tennis API "https://tennis.bzzoiro.com/"
BASE_URL = "https://tennis.bzzoiro.com/api"
headers = {"Authorization": f"Token {tennis_api_token}"}

#Creating a client to access the Supabase database
supabase = create_client(supabase_url, supabase_key)

#Method for preparing a string (first name and last name):
# - Removes all whitespaces
def prepare_string(s):
    return re.sub(r"\s+", "", s)

#Method for checking if the username is unique in the database
def username_is_unique(username):
    response = supabase.table("profiles").select("id").eq("username", username).execute()

    return not response.data

#Method for checking if the email is unique in the database
def email_is_unique(email):
    response = supabase.table("profiles").select("id").eq("email", email).execute()

    return not response.data

#Method for getting a page of data of players from API:
# - Returns list of players and next page URL
def get_players_page(url):
    resp = requests.get(url, headers=headers)
    data = resp.json()
    return data["results"], data.get("next")

#Method for creating an account for the tennis player
# - Validates input data for the signup
# - Creates a new user in Supabase Auth
# - Inserts additional user information in the profiles table.
# - Passwords and emails are autogenerated
def create_account(first_name, last_name):
    #Remove spaces from the string
    first_name_for_generating = prepare_string(first_name)
    last_name_for_generating = prepare_string(last_name)

    generated_email = f"{first_name_for_generating}.{last_name_for_generating}@courtiqproject.test"
    generated_password = f"32q5jfnfgs3232{first_name_for_generating}"
    generated_username = f"{first_name_for_generating}.{last_name_for_generating}"

    if not username_is_unique(generated_username):
        return False

    if not email_is_unique(generated_email):
        return False

    #Performing sign_up with the supabase.auth
    try:
        auth_response = supabase.auth.sign_up({
            "email": generated_email,
            "password": generated_password
        })
    except Exception as e:
        return False

    user = auth_response.user

    #Inserting into the profile table additional information about the user and linking user Supabase table and profiles table with user.id
    insert_response = supabase.table("profiles").insert({
        "id": user.id,
        "username": generated_username,
        "first_name": first_name,
        "last_name": last_name,
        "role": "ATHLETE",
        "email": generated_email
    }).execute()

    return True

#Main method
# - Creates n additional tennis players
# - Calls get_players_page(url) and create_account(first_name, last_name) helper functions
# - Going through the page of players and choosing accounts to create
def main():
    #n is a number of additional players from API to add (players added in alphabet order, starting with the letter "a")
    n = 1
    created = 0
    url = f"{BASE_URL}/players/"

    #Store already seen players
    seen = set()

    #While number of created users didn't reach the limit
    while created < n:
        players, url = get_players_page(url)

        for player in players:
            name = player.get("name")

            #If enough was created, stop
            if created >= n:
                break

            #Skipping players with inappropriate symbols in a name
            if re.search(r"[^a-zA-ZÀ-ÿ' -]", name) or " " not in name:
                continue

            #Splitting the full name into the last and first name
            parts = name.strip().split(" ", 1)
            first_name = parts[0]
            last_name = parts[1]

            #Checking if first name and last name exists
            if not first_name or not last_name:
                continue

            #Checking if the tennis player was already seen (processed)
            key = (first_name, last_name)
            if key in seen:
                continue
            seen.add(key)

            #Checking if the account was created for the player
            if create_account(first_name, last_name):
                created += 1

if __name__ == "__main__":
    main()